# Generated by Django 6.0.5 on 2026-05-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
